{% set name = "pydantic-settings-sops" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydantic_settings_sops-{{ version }}.tar.gz
  sha256: d3978e0cc0e8398e451ee85660e0fc871abbbe7e2d5c9cd7a07f3479dd56d64f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.10
    - pydantic-settings >=2.5.2,<3
    - sopsy >=1.0.0,<2

test:
  imports:
    - pydantic_settings_sops
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pavelzw/pydantic-settings-sops
  summary: SOPS extension for pydantic-settings
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
